services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    labels:
      - com.portto=datebase
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
  redis:
    image: redis:7.2.3
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  transaction-service:
    image: transaction-service:v0.0.1
    restart: always
    env_file:
      - .env
    volumes:
      - ./api/transaction-service/deployment/application.yaml:/app/project/application.yaml
    depends_on:
      - db
      - redis
  block-service:
    image: block-service:v0.0.1
    restart: always
    env_file:
      - .env
    volumes:
      - ./api/block-service/deployment/application.yaml:/app/project/application.yaml
    depends_on:
      - db
      - redis
  monitor-service:
    image: monitor-service:v0.0.1
    restart: always
    env_file:
      - .env
    volumes:
      - ./api/monitor-service/deployment/application.yaml:/app/project/application.yaml
    depends_on:
      - db
      - redis
  graph-service:
    image: graph-service:v0.0.1
    restart: always
    env_file:
      - .env
    volumes:
      - ./api/graph-service/deployment/application.yaml:/app/project/application.yaml
    ports:
      - ${REST_PORT}:${REST_PORT}
    depends_on:
      - db
      - redis
    