// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Block struct {
	BlockNum     string   `json:"blockNum"`
	BlockHash    string   `json:"blockHash"`
	BlockTime    string   `json:"blockTime"`
	ParentHash   string   `json:"parentHash"`
	Transactions []string `json:"transactions"`
	Stable       bool     `json:"stable"`
}

type Blocks struct {
	Blocks []*Block `json:"blocks"`
}

type Log struct {
	TxHash string `json:"txHash"`
	Index  uint32 `json:"index"`
	Data   string `json:"data"`
}

type Transaction struct {
	TxHash string `json:"txHash"`
	From   string `json:"from"`
	To     string `json:"to"`
	Nonce  string `json:"nonce"`
	Data   string `json:"data"`
	Value  string `json:"value"`
	Logs   []*Log `json:"logs"`
}
