// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package repository

var TableNames = struct {
	SchemaMigrations string
	TBlock           string
	TLog             string
	TTransaction     string
}{
	SchemaMigrations: "schema_migrations",
	TBlock:           "t_block",
	TLog:             "t_log",
	TTransaction:     "t_transaction",
}
